<a href="https://colab.research.google.com/github/WandersonGustavo/Imersao_Alura/blob/main/dataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#criando var
y = "hello world"
print(y)

hello world


In [ ]:
y=20
x=2
z=(y*x)
print(z)
xx="ola mundo"
#yy=2023
zz="vai ser iradoooo"
print(xx+zz)

40
ola mundovai ser iradoooo


In [ ]:
print("digite")
i=input()
print(i)
var=input("digite valor")
print(var)
var1=float(var)
print(var1)

digite
oi
oi
digite valor255
255
255.0


In [ ]:
#DECISÃO
nota=input()
if nota>=7.0:
  print("Sua nota foi:",nota,"APR")
elif nota<7.0 and nota>=5.0:
  print("Sua nota foi:",nota,": DEP")
else:
  print("Sua nota foi:",nota,"REP")

In [ ]:
count =1
while count <=5:
  print(count)
  count+=1
print("***********************************")
for n in range(2,23):
  if(n==16):
    continue #pulará o 16, break terminaria no 16
  print(n)
print("##########")
lst2=list(range(1,11))
lst=[1,"ola",False,[1,2,"cinco",True],lst2] #lista guarda varios tipos diferentes
print(lst[4])
print("##########")
#DICIONARIOS & SET"S
notas={"val1":5.5,"var2":7.5,"var3":8.5}
print(notas["val1"])#imprimindo valor da chave val1
print("val1"in notas)#verificar se existe no dic, será boolean
notas["val4"]=9.5 #incluir no dic 
print(notas.get("val4"))#pegar valor 
print("##############")
#SET 
bd={"v","t","u"}
print(len(bd))
bd.add("r")
print(bd)
print(len(bd))
#tupla ,USAM () e ñ pode alterar
tp=(1,2,35,4)
print(type(tp))


In [6]:
import numpy as np
#matriz multiD
md=np.array([1,2,3,4])
print(md)
mdd=np.array([1.5,25.5,3.0,40.8,5.5,6.6,7.85],dtype = np.float64)
#convertendo type
mdn=mdd.astype(int)#mudando tipo
print(mdd)
print(mdn)#resultado
print("############33")
#criando matriz
zeros=np.zeros([4,3])
print(zeros)
diag=np.eye(4)
print(diag)#diag principalcom 1
print("########################")
rand=np.random.random((4,4))#valores aleat
print(rand)
print("########################")
gr=np.random.default_rng(1)#nums aleats padrao, o 1 é a semente
print(gr)
print(zeros[1][1])#printar valor especifíco
print(diag+rand)#soma de matrizs
s=rand.transpose
s1=rand.transpose
print(rand+rand)
print("###################")
print(rand)

[1 2 3 4]
[ 1.5  25.5   3.   40.8   5.5   6.6   7.85]
[ 1 25  3 40  5  6  7]
############33
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
########################
[[0.8522984  0.85739361 0.0135689  0.15808159]
 [0.64876199 0.216631   0.02662342 0.54670288]
 [0.871544   0.77936115 0.63509192 0.09159598]
 [0.82497933 0.84120368 0.22392438 0.66149268]]
########################
Generator(PCG64)
0.0
[[1.8522984  0.85739361 0.0135689  0.15808159]
 [0.64876199 1.216631   0.02662342 0.54670288]
 [0.871544   0.77936115 1.63509192 0.09159598]
 [0.82497933 0.84120368 0.22392438 1.66149268]]
[[1.7045968  1.71478721 0.0271378  0.31616317]
 [1.29752399 0.433262   0.05324684 1.09340576]
 [1.74308801 1.5587223  1.27018384 0.18319195]
 [1.64995866 1.68240736 0.44784876 1.32298537]]
###################
[[0.8522984  0.85739361 0.0135689  0.15808159]
 [0.64876199 0.216631   0.02662342 0.54670288]
 [0.871544   0.77936115 0.63509192 0.09159598]