<a href="https://colab.research.google.com/github/WandersonGustavo/Imersao_Alura/blob/main/dataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#criando var
y = "hello world"
print(y)

hello world


In [10]:
y=20
x=2
z=(y*x)
print(z)
xx="ola mundo"
#yy=2023
zz="vai ser iradoooo"
print(xx+zz)

40
ola mundovai ser iradoooo


In [12]:
print("digite")
i=input()
print(i)
var=input("digite valor")
print(var)
var1=float(var)
print(var1)

digite
oi
oi
digite valor255
255
255.0


In [ ]:
#DECISÃO
nota=input()
if nota>=7.0:
  print("Sua nota foi:",nota,"APR")
elif nota<7.0 and nota>=5.0:
  print("Sua nota foi:",nota,": DEP")
else:
  print("Sua nota foi:",nota,"REP")

In [ ]:
count =1
while count <=5:
  print(count)
  count+=1
print("***********************************")
for n in range(2,23):
  if(n==16):
    continue #pulará o 16, break terminaria no 16
  print(n)
print("##########")
lst2=list(range(1,11))
lst=[1,"ola",False,[1,2,"cinco",True],lst2] #lista guarda varios tipos diferentes
print(lst[4])
print("##########")
#DICIONARIOS & SET"S
notas={"val1":5.5,"var2":7.5,"var3":8.5}
print(notas["val1"])#imprimindo valor da chave val1
print("val1"in notas)#verificar se existe no dic, será boolean
notas["val4"]=9.5 #incluir no dic 
print(notas.get("val4"))#pegar valor 
print("##############")
#SET 
bd={"v","t","u"}
print(len(bd))
bd.add("r")
print(bd)
print(len(bd))
#tupla ,USAM () e ñ pode alterar
tp=(1,2,35,4)
print(type(tp))


In [58]:
import numpy as np
#matriz multiD
md=np.array([1,2,3,4])
print(md)
mdd=np.array([1.5,25.5,3.0,40.8,5.5,6.6,7.85],dtype = np.float64)
#convertendo type
mdn=mdd.astype(int)#mudando tipo
print(mdd)
print(mdn)#resultado
print("############33")
#criando matriz
zeros=np.zeros([4,3])
print(zeros)
diag=np.eye(4)
print(diag)#diag principalcom 1
print("########################")
rand=np.random.random((4,4))#valores aleat
print(rand)
print("########################")
gr=np.random.default_rng(1)#nums aleats padrao, o 1 é a semente
print(gr)
print(zeros[1][1])#printar valor especifíco
print(diag+rand)#soma de matrizs
s=rand.transpose

[1 2 3 4]
[ 1.5  25.5   3.   40.8   5.5   6.6   7.85]
[ 1 25  3 40  5  6  7]
############33
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
########################
[[0.30793852 0.18652373 0.03551133 0.47580283]
 [0.66788426 0.76899584 0.82622825 0.82557476]
 [0.69510675 0.24951462 0.24030613 0.63118304]
 [0.40153088 0.6879018  0.77571568 0.64963921]]
########################
Generator(PCG64)
0.0
[[1.30793852 0.18652373 0.03551133 0.47580283]
 [0.66788426 1.76899584 0.82622825 0.82557476]
 [0.69510675 0.24951462 1.24030613 0.63118304]
 [0.40153088 0.6879018  0.77571568 1.64963921]]
